### ISSUE TITLE
Not working as intended

### ISSUE THREAD

**Issue by catactive** [L413/Cursor-Changer#1]
I'm trying to figure this out and how to fix it, but now whenever I use the bookmarklet and click on the cursor I want, it will display on the menu but not the webpage.

**Comment by L413** [comment]
Yes, I am aware that happens sometimes, some webpages wont let you change stuff like that but it might have been fixed in the is update.

**Comment by catactive** [comment]
Nevermind forgot to download the new version

**Comment by L413** [comment]
ok
