### ISSUE TITLE
Blocked

### ISSUE THREAD

**Issue by adsbona** [L413/Cursor-Changer#2]
hi i was just wondering if you could update your old bookmark because in the new bookmark the website glitch it uses is blocked for me so i cant use it. It's ok if its to much trouble to update your old bookmark or make a new one.

**Comment by L413** [comment]
Yea, ik glitch projects often get blocked unfortunately it will probably just get blocked again so I'm not going to change the URL. Sorry :(

**Comment by adsbona** [comment]
ok its fine I can still use the old bookmark.js file

**Comment by L413** [comment]
good idea
